### ISSUE TITLE
commit 3277f3c  ("Attempting to add CSSModule support") introduces a bug with regards to fileytpe detection

### ISSUE THREAD

**Issue by wimstefan** [amadeus/vim-css#2]
When editing different filetypes (vim and sh come to mind) all in a sudden the commentstring used for those filetypes is `/*%s*/` instead of `"%s` and `#%s` respectively. 

By disabling all plugins I use and enabling them one by one I found out that this is caused by your plugin. I can't tell you precisely what's causing the problem but with `git bisect` I could at least detect when the problems started ... 

Could you please have a look at it?

**Comment by da-x** [comment]
From the looks of the diff of 3277f3c, https://github.com/amadeus/vim-css/pull/3 probably fixes it.

**Comment by wimstefan** [comment]
Thanks for coming back to my report but I've stopped using your module and can't check it.
Thanks for all your efforts though 😃
