### ISSUE TITLE
Bracket error defining grid template names?

### ISSUE THREAD

**Issue by jxpx777** [amadeus/vim-css#6]
I'm working with CSS grid in a new personal project and using `grid-template-columns` with [named columns](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Grid_layout_using_named_grid_lines), which vim-css seems to flag as a syntax error on the brackets.

![CleanShot 2024-01-10 at 10 13 00@2x](https://github.com/amadeus/vim-css/assets/24182/088f05a2-bd38-4da6-b771-f56607140f6a)

Here's the file:
[grid-column-names.css.txt](https://github.com/amadeus/vim-css/files/13891392/grid-column-names.css.txt)

**Comment by amadeus** [comment]
Oh wow someone uses this! Oki, thanks for the example, I’ll look at fixing this soon

**Comment by amadeus** [comment]
I have a fix in 6a82e5a7c1442cd2378f04a14f1e873d78420d5e, thanks for the report!

It was mostly a temporary quick fix since I wanted to get you unblocked but will need to revisit a bunch of this new syntax stuff in the future.
